version: '3'

services:
  postgres:
    image: postgres:14
    command: postgres -c log_statement=all
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=pokemon_final_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Runsho%232323
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  worker:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PIP_DEFAULT_TIMEOUT=100
      - DATABASE=postgres
    ports:
      - '8000:8000'
    volumes:
      - ./mo_services:/mo_services/mo_services
      - ./tests:/tests
      - ${HOME}/.gitconfig:/home/user/.gitconfig:ro
      - ${HOME}/.ssh:/home/user/.ssh:ro
    depends_on:
      - postgres

volumes:
  postgres_data:




