# Generated by Django 4.1.6 on 2023-02-13 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('mon_id', models.CharField(max_length=250)),
                ('evolution_chain_id', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('first_type', models.CharField(max_length=250)),
                ('second_type', models.CharField(blank=True, max_length=250)),
                ('height', models.CharField(max_length=250)),
                ('weight', models.CharField(max_length=250)),
                ('hp', models.CharField(max_length=250)),
                ('attack', models.CharField(max_length=250)),
                ('defense', models.CharField(max_length=250)),
                ('special_attack', models.CharField(max_length=250)),
                ('special_defense', models.CharField(max_length=250)),
                ('speed', models.CharField(max_length=250)),
                ('evolutions_list', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Evolutions',
            fields=[
                ('evolution_chain_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('evolution_type', models.CharField(max_length=250)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_rest_app.pokemons')),
            ],
        ),
    ]
