# Generated by Django 4.1.6 on 2023-02-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemons',
            name='attack',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='defense',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='evolutions_list',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='height',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='hp',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='special_attack',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='special_defense',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='speed',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='weight',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
