# Generated by Django 4.1.6 on 2023-02-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemons',
            name='evolution_type',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
