# Generated by Django 4.1.6 on 2023-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_rest_app', '0003_alter_evolutions_evolution_chain_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutions',
            name='evolution_chain_id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evolutions',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='mon_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
